### ISSUE TITLE
Request to specify directory of feature files.

### ISSUE THREAD

**Issue by tendryll** [bmsantos/cola-tests#63]
Please provide the option to specify the a directory where feature files are located.

 ```java
@Features(dir="classpath:features/", features={"feature1", "feature2"})
```

**Comment by bmsantos** [comment]
@tendryll By the way, the final format ended up being:

```java
@Features(classpath = "/path/to/stories", value = "cp-gherkin-example")
```
If classpath property is not defined, then it will look for feature file in test class package path.
If classpath is defined, then it will look for the file within the specified classpath directory.

At the moment it is not allowed to fetch the features files from any other place other than the classpath. This might change once the Feature server is done and feature files can be specified by URL and fetch directly from the server. That will come closer to version 1.0 though.

Let me know if as it is works for you so that I can close the ticket. Thanks.
